### ISSUE TITLE
Additional classes ignored when first argument only has strings

### ISSUE THREAD

**Issue by royalicing** [pocotan001/bem-classnames#4]
``` JavaScript
var classes = bem({
    name: 'name'
}, 'additional');
```

Expected result:
'name additional'

Actual result:
'name'

**Comment by pocotan001** [comment]
@BurntCaramel I've released the fix in v1.0.7. Thank you for reporting the problem!

**Comment by royalicing** [comment]
That’s alright! I had a fix in progress, just needed to install mocha and create a test – was going to finish it the next day. Thanks for the super speedy response!
